### ISSUE TITLE
Over v1.7.0 can't find rake-12.0.0 

### ISSUE THREAD

**Issue by yusukesasamo** [cloudfoundry/ruby-buildpack#93]
I couldn't solve this issue. I would appreciate if you could help me:cry:

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.31.0+b35df905d.2017-09-15

What version of the buildpack you are using?
Over v1.7.0

If you were attempting to accomplish a task, what was it you were attempting to do?
When I build new app with ruby-buildpack v1.7.0, couldn't find rake12.0.0 but v1.6.47 could find rake12.0.0.

What did you expect to happen?
Could find rake12.0.0.

Please confirm where necessary:
When I did `cf push` the following error happen in v1.7.0
* [] My log includes an error message
```
       Bundle complete! 37 Gemfile dependencies, 155 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into `/tmp/contents471890481/deps/0/vendor_bundle`
-----> Regenerating bundler binstubs...
       Cleaning up the bundler cache.
-----> Creating runtime environment
Bundler::GemNotFound: Could not find rake-12.0.0 in any of the sources
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler/spec_set.rb:88:in `block in materialize'
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler/spec_set.rb:82:in `map!'
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler/spec_set.rb:82:in `materialize'
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler/definition.rb:170:in `specs'
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler/definition.rb:237:in `specs_for'
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler/definition.rb:226:in `requested_specs'
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler/runtime.rb:108:in `block in definition_method'
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler/runtime.rb:20:in `setup'
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler.rb:107:in `setup'
  /tmp/contents471890481/deps/0/bundler/gems/bundler-1.16.0/lib/bundler/setup.rb:20:in `<top (required)>'
  /tmp/contents471890481/deps/0/ruby/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /tmp/contents471890481/deps/0/ruby/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       **ERROR** Unable to write profile.d: Running 'rake secret'%!(EXTRA *exec.ExitError=exit status 1)
Failed to compile droplet: Failed to run all supply scripts: exit status 15
Staging failed: STG: Exited with status 223
Exit status 223
Stopping instance 1c9b6135-62f6-4c01-9b85-bcab05a0a641
Destroying container
Successfully destroyed container
```

**Comment by dgodd** [comment]
@yusukesasamo Could you please try the latest version of the buildpack (v1.7.13), I believe this problem has been fixed

**Comment by yusukesasamo** [comment]
@dgodd I've tried to use latest version of the build back (v1.7.13) but it seems this issue is not fixed.:cry:

**Comment by sclevine** [comment]
@yusukesasamo can you provide all of the staging output, as well as a sample app that fails?

**Comment by yusukesasamo** [comment]
This is output
```
Creating container
Successfully created container
Downloading app package...
Downloaded app package (42.3M)
Staging...
-----> Download go 1.9.1
-----> Running go build supply
-----> Ruby Buildpack version 1.7.13
-----> Supplying Ruby
-----> Installing bundler 1.16.1
       Download [https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler-1.16.1-8e9f1a6e.tgz]
       **WARNING** You have not declared a Ruby version in your Gemfile.
       Defaulting to 2.4.3
       See http://docs.cloudfoundry.org/buildpacks/ruby/index.html#runtime for more information.
-----> Installing ruby 2.4.3
       Download [https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.3-linux-x64-79b34eab.tgz]
-----> Update rubygems from 2.6.14 to 2.7.6
-----> Installing rubygems 2.7.6
       Download [https://buildpacks.cloudfoundry.org/dependencies/rubygems/rubygems-2.7.6-67f714a5.tgz]
-----> Installing node 6.13.0
       Download [https://buildpacks.cloudfoundry.org/dependencies/node/node-6.13.0-linux-x64-2724bdf3.tgz]
       It contains local state like the location of the installed bundle
       as well as configured git local gems, and other settings that should
       remove the `.bundle/` folder from your repo and add it to your `.gitignore` file.
       **WARNING** You have the `.bundle/config` file checked into your repository
       not be shared between multiple checkouts of a single repo. Please
       Running: bundle install --without development:test --jobs=4 --retry=4 --path /tmp/contents628441374/deps/0/vendor_bundle --binstubs /tmp/contents628441374/deps/0/binstubs --deployment
-----> Installing dependencies using bundler 1.16.1
       Fetching gem metadata from http://stg-xxxxxxx.xxx.xx.xxxxxxx/content/groups/gems_public/.
       
       
       Fetching rake 12.0.0
       Fetching concurrent-ruby 1.0.5
       Fetching minitest 5.11.1
       Installing minitest 5.11.1
       Installing concurrent-ruby 1.0.5
       Installing rake 12.0.0
       Fetching thread_safe 0.3.6
       Fetching builder 3.2.3
       Installing thread_safe 0.3.6
       Fetching erubi 1.7.0
       Installing builder 3.2.3
       Fetching mini_portile2 2.3.0
       Installing erubi 1.7.0
       Fetching crass 1.0.3
       Fetching rack 2.0.3
       Installing mini_portile2 2.3.0
       Fetching nio4r 2.2.0
       Installing crass 1.0.3
       Fetching websocket-extensions 0.1.3
       Installing rack 2.0.3
       Installing nio4r 2.2.0 with native extensions
       Installing websocket-extensions 0.1.3
       Fetching mini_mime 1.0.0
       Fetching arel 8.0.0
       Installing mini_mime 1.0.0
       Fetching public_suffix 3.0.1
       Installing arel 8.0.0
       Installing public_suffix 3.0.1
       Fetching ast 2.3.0
       Fetching execjs 2.7.0
       Installing ast 2.3.0
       Fetching ice_nine 0.11.2
       Installing execjs 2.7.0
       Fetching bcrypt 3.1.11
       Installing ice_nine 0.11.2
       Installing bcrypt 3.1.11 with native extensions
       Fetching bindex 0.5.0
       Installing bindex 0.5.0 with native extensions
       Fetching rb-fsevent 0.10.2
       Installing rb-fsevent 0.10.2
       Fetching ffi 1.9.18
       Installing ffi 1.9.18 with native extensions
       Fetching method_source 0.9.0
       Installing method_source 0.9.0
       Fetching thor 0.20.0
       Fetching brakeman 4.1.1
       Installing thor 0.20.0
       Using bundler 1.16.1
       Fetching byebug 9.1.0
       Installing brakeman 4.1.1
       Installing byebug 9.1.0 with native extensions
       Fetching mime-types-data 3.2016.0521
       Installing mime-types-data 3.2016.0521
       Fetching cliver 0.3.2
       Installing cliver 0.3.2
       Fetching equalizer 0.0.11
       Installing equalizer 0.0.11
       Fetching coderay 1.1.2
       Installing coderay 1.1.2
       Fetching coffee-script-source 1.12.2
       Installing coffee-script-source 1.12.2
       Fetching deep_merge 1.1.1
       Installing deep_merge 1.1.1
       Fetching dry-equalizer 0.2.0
       Installing dry-equalizer 0.2.0
       Fetching inflecto 0.0.2
       Installing inflecto 0.0.2
       Fetching database_cleaner 1.6.2
       Installing database_cleaner 1.6.2
       Fetching orm_adapter 0.5.0
       Installing orm_adapter 0.5.0
       Fetching devise-bootstrap-views 0.0.11
       Installing devise-bootstrap-views 0.0.11
       Fetching net-ldap 0.11
       Installing net-ldap 0.11
       Fetching diff-lcs 1.3
       Installing diff-lcs 1.3
       Fetching erubis 2.7.0
       Installing erubis 2.7.0
       Fetching path_expander 1.0.2
       Installing path_expander 1.0.2
       Fetching sexp_processor 4.10.0
       Installing sexp_processor 4.10.0
       Fetching formatador 0.2.5
       Installing formatador 0.2.5
       Fetching gherkin 4.1.3
       Installing gherkin 4.1.3
       Fetching ruby_dep 1.5.0
       Installing ruby_dep 1.5.0
       Fetching lumberjack 1.0.12
       Installing lumberjack 1.0.12
       Fetching nenv 0.3.0
       Installing nenv 0.3.0
       Fetching shellany 0.0.1
       Installing shellany 0.0.1
       Fetching guard-compat 1.2.1
       Installing guard-compat 1.2.1
       Fetching rspec-support 3.7.0
       Installing rspec-support 3.7.0
       Fetching multi_json 1.13.1
       Installing multi_json 1.13.1
       Fetching json 1.8.6
       Installing json 1.8.6 with native extensions
       Fetching libv8 3.16.14.19 (x86_64-linux)
       Installing libv8 3.16.14.19 (x86_64-linux)
       Fetching mysql2 0.4.10
       Installing mysql2 0.4.10 with native extensions
       Fetching parallel 1.12.1
       Installing parallel 1.12.1
       Fetching phantomjs 2.1.1.0
       Installing phantomjs 2.1.1.0
       Fetching powerpack 0.1.1
       Installing powerpack 0.1.1
       Fetching rdoc 4.3.0
       Installing rdoc 4.3.0
       Fetching ref 2.0.0
       Installing ref 2.0.0
       Fetching ruby-progressbar 1.9.0
       Installing ruby-progressbar 1.9.0
       Fetching unicode-display_width 1.3.0
       Installing unicode-display_width 1.3.0
       Fetching tty-which 0.3.0
       Installing tty-which 0.3.0
       Fetching tilt 2.0.8
       Installing tilt 2.0.8
       Fetching temple 0.8.0
       Installing temple 0.8.0
       Fetching turbolinks-source 5.1.0
       Installing turbolinks-source 5.1.0
       Fetching rainbow 2.2.2
       Installing rainbow 2.2.2 with native extensions
       Fetching i18n 0.9.1
       Installing i18n 0.9.1
       Fetching dry-configurable 0.7.0
       Fetching dry-core 0.4.2
       Installing dry-configurable 0.7.0
       Fetching tzinfo 1.2.4
       Fetching descendants_tracker 0.0.4
       Installing dry-core 0.4.2
       Fetching nokogiri 1.8.1
       Installing descendants_tracker 0.0.4
       Fetching websocket-driver 0.6.5
       Installing tzinfo 1.2.4
       Installing websocket-driver 0.6.5 with native extensions
       Fetching rack-test 0.6.3
       Installing rack-test 0.6.3
       Fetching warden 1.2.7
       Installing nokogiri 1.8.1 with native extensions
       Fetching sprockets 3.7.1
       Installing warden 1.2.7
       Fetching mail 2.7.0
       Installing sprockets 3.7.1
       Fetching addressable 2.5.2
       Installing addressable 2.5.2
       Installing mail 2.7.0
       Fetching parser 2.4.0.2
       Fetching autoprefixer-rails 7.2.5
       Installing parser 2.4.0.2
       Fetching uglifier 4.1.3
       Installing autoprefixer-rails 7.2.5
       Installing uglifier 4.1.3
       Fetching select2-rails 4.0.3
       Fetching mime-types 3.1
       Installing select2-rails 4.0.3
       Installing mime-types 3.1
       Fetching pry 0.11.3
       Fetching coffee-script 2.4.1
       Installing pry 0.11.3
       Installing coffee-script 2.4.1
       Fetching ruby_parser 3.10.1
       Fetching notiffany 0.1.1
       Installing ruby_parser 3.10.1
       Fetching rspec-core 3.7.1
       Installing notiffany 0.1.1
       Fetching rspec-expectations 3.7.0
       Installing rspec-core 3.7.1
       Installing rspec-expectations 3.7.0
       Fetching rspec-mocks 3.7.0
       Fetching rb-inotify 0.9.10
       Installing rspec-mocks 3.7.0
       Installing rb-inotify 0.9.10
       Fetching therubyracer 0.12.3
       Fetching slim 3.0.9
       Installing therubyracer 0.12.3 with native extensions
       Installing slim 3.0.9
       Fetching turbolinks 5.1.0
       Installing turbolinks 5.1.0
       Fetching dry-container 0.6.0
       Installing dry-container 0.6.0
       Fetching sdoc 0.4.2
       Installing sdoc 0.4.2
       Fetching axiom-types 0.1.1
       Installing axiom-types 0.1.1
       Fetching coercible 1.0.0
       Installing coercible 1.0.0
       Fetching activesupport 5.1.3
       Installing activesupport 5.1.3
       Fetching launchy 2.4.3
       Installing launchy 2.4.3
       Fetching rubocop 0.52.1
       Installing rubocop 0.52.1
       Fetching flay 2.10.0
       Installing flay 2.10.0
       Fetching flog 4.6.1
       Installing flog 4.6.1
       Fetching rspec_junit_formatter 0.3.0
       Installing rspec_junit_formatter 0.3.0
       Fetching rspec 3.7.0
       Installing rspec 3.7.0
       Fetching sass-listen 4.0.0
       Installing sass-listen 4.0.0
       Fetching listen 3.1.5
       Installing listen 3.1.5
       Fetching dry-logic 0.4.2
       Fetching virtus 1.0.5
       Installing dry-logic 0.4.2
       Fetching globalid 0.4.1
       Installing virtus 1.0.5
       Installing globalid 0.4.1
       Fetching activemodel 5.1.3
       Fetching factory_girl 4.9.0
       Installing activemodel 5.1.3
       Installing factory_girl 4.9.0
       Fetching jbuilder 2.7.0
       Fetching rubocop-checkstyle_formatter 0.4.0
       Installing jbuilder 2.7.0
       Fetching turnip 3.0.0
       Installing rubocop-checkstyle_formatter 0.4.0
       Fetching sass 3.5.5
       Installing turnip 3.0.0
       Fetching guard 2.14.2
       Installing sass 3.5.5
       Installing guard 2.14.2
       Fetching rails-dom-testing 2.0.3
       Installing rails-dom-testing 2.0.3
       Fetching loofah 2.1.1
       Fetching xpath 2.1.0
       Installing xpath 2.1.0
       Installing loofah 2.1.1
       Fetching dry-types 0.12.2
       Fetching activejob 5.1.3
       Installing dry-types 0.12.2
       Installing activejob 5.1.3
       Fetching codeclimate-engine-rb 0.4.1
       Fetching activerecord 5.1.3
       Installing codeclimate-engine-rb 0.4.1
       Fetching guard-rspec 4.7.3
       Installing activerecord 5.1.3
       Installing guard-rspec 4.7.3
       Fetching bootstrap-sass 3.3.7
       Fetching capybara 2.13.0
       Installing bootstrap-sass 3.3.7
       Installing capybara 2.13.0
       Fetching rails-html-sanitizer 1.0.3
       Installing rails-html-sanitizer 1.0.3
       Fetching dry-validation 0.11.1
       Fetching reek 4.7.3
       Installing dry-validation 0.11.1
       Fetching actionview 5.1.3
       Installing reek 4.7.3
       Installing actionview 5.1.3
       Fetching poltergeist 1.15.0
       Fetching config 1.6.1
       Installing config 1.6.1
       Fetching rubycritic 3.3.0
       Installing poltergeist 1.15.0
       Fetching actionpack 5.1.3
       Installing rubycritic 3.3.0
       Installing actionpack 5.1.3
       Fetching actioncable 5.1.3
       Installing actioncable 5.1.3
       Fetching actionmailer 5.1.3
       Fetching railties 5.1.3
       Installing actionmailer 5.1.3
       Fetching sprockets-rails 3.2.1
       Installing railties 5.1.3
       Installing sprockets-rails 3.2.1
       Fetching jquery-rails 4.3.1
       Fetching coffee-rails 4.2.2
       Installing coffee-rails 4.2.2
       Fetching responders 2.4.0
       Installing jquery-rails 4.3.1
       Fetching factory_girl_rails 4.9.0
       Installing responders 2.4.0
       Fetching font-awesome-rails 4.7.0.3
       Installing factory_girl_rails 4.9.0
       Fetching jquery-ui-rails 6.0.1
       Installing font-awesome-rails 4.7.0.3
       Fetching rails 5.1.3
       Installing jquery-ui-rails 6.0.1
       Installing rails 5.1.3
       Fetching rspec-rails 3.7.2
       Installing rspec-rails 3.7.2
       Fetching sass-rails 5.0.7
       Fetching slim-rails 3.1.3
       Installing sass-rails 5.0.7
       Fetching teaspoon 1.1.5
       Installing slim-rails 3.1.3
       Fetching web-console 3.5.1
       Installing teaspoon 1.1.5
       Installing web-console 3.5.1
       Fetching bootstrap-validator-rails 0.5.3
       Fetching devise 4.4.0
       Installing bootstrap-validator-rails 0.5.3
       Installing devise 4.4.0
       Fetching teaspoon-mocha 2.3.3
       Installing teaspoon-mocha 2.3.3
       Fetching devise_ldap_authenticatable 0.8.5
       Installing devise_ldap_authenticatable 0.8.5
       Bundle complete! 37 Gemfile dependencies, 155 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into `/tmp/contents628441374/deps/0/vendor_bundle`
-----> Regenerating bundler binstubs...
       Cleaning up the bundler cache.
-----> Creating runtime environment
Bundler::GemNotFound: Could not find rake-12.0.0 in any of the sources
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:88:in `block in materialize'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:82:in `map!'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:82:in `materialize'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:170:in `specs'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:237:in `specs_for'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:226:in `requested_specs'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:108:in `block in definition_method'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:20:in `setup'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler.rb:107:in `setup'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/setup.rb:20:in `<top (required)>'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /tmp/contents628441374/deps/0/ruby/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
       **ERROR** Unable to write profile.d: Running 'rake secret'%!(EXTRA *exec.ExitError=exit status 1)
Failed to compile droplet: Failed to run all supply scripts: exit status 15
Exit status 223
Staging failed: STG: Exited with status 223
Stopping instance 92bd3841-cf1b-4809-8ecd-3390fda61ba9
Destroying container
Successfully destroyed container
```

Sorry I can't provide my app because this app is internal tool for my company, but I can provide Gemfile the following.

```
# frozen_string_literal: true
source "http://xxx-xxxxxx.xxx.xx.xxxxx/content/groups/gems_public/"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "5.1.3"
# Use Slim for html template engine
gem "slim-rails"
# Use SCSS for stylesheets
gem "bootstrap-sass", "~> 3.3.6"
gem "font-awesome-rails"
gem "sass-rails", "~> 5.0"

gem "bootstrap-validator-rails", "~> 0.5.3"
# Use Uglifier as compressor for JavaScript assets
gem "uglifier", ">= 1.3.0"
# Use CoffeeScript for .coffee assets and views
gem "coffee-rails", ">= 4.0.0"
# See https://github.com/rails/execjs#readme for more supported runtimes
gem "therubyracer", platforms: :ruby

# Use jquery as the JavaScript library
gem "jquery-rails"
gem "jquery-ui-rails"
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem "turbolinks"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.0"
# bundle exec rake doc:rails generates the API under doc/api.
gem "sdoc", "~> 0.4.0", group: :doc

# LDAP
gem "devise"
gem "devise-bootstrap-views"
gem "devise_ldap_authenticatable"

# Call 'byebug' anywhere in the code to stop execution and get a debugger console
gem "byebug"

# Searchable pull down list
gem "select2-rails"

group :development, :devci, :stgci, :test do
  gem "brakeman"
  gem "capybara", "~> 2.13.0"
  gem "database_cleaner", "~> 1.6.1"
  gem "factory_girl_rails"
  gem "guard-rspec"
  gem "phantomjs", require: "phantomjs/poltergeist"
  gem "poltergeist", "~> 1.15.0"
  gem "rspec-rails"
  gem "rspec_junit_formatter"
  gem "rubocop"
  gem "rubocop-checkstyle_formatter", require: false
  gem "rubycritic", require: false
  gem "teaspoon-mocha", "~> 2.3.3"
  gem "turnip", "~> 3.0.0"
end

group :development, :dev do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem "web-console", ">= 3.3.0"
end

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
end

gem "config"
gem "mysql2", "~> 0.4.5"
```

Does it make sense??

**Comment by dgodd** [comment]
@yusukesasamo I attempted to see the error you discussed by copying that Gemfile into an app, but hit other snags. If you can create an app which you can share which exhibits the problem then we should be able to fix it for you.

**Comment by yusukesasamo** [comment]
@dgodd I made sample app.
https://github.com/yusukesasamo/rails-sample/tree/master/test-app
This app also has same issue the following.
```
Creating container
Successfully created container
Downloading app package...
Downloaded app package (27.7K)
Staging...
-----> Download go 1.9.1
-----> Running go build supply
-----> Ruby Buildpack version 1.7.13
-----> Supplying Ruby
       Download [https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler-1.16.1-8e9f1a6e.tgz]
-----> Installing bundler 1.16.1
       **WARNING** You have not declared a Ruby version in your Gemfile.
       Defaulting to 2.4.3
       See http://docs.cloudfoundry.org/buildpacks/ruby/index.html#runtime for more information.
       Download [https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.3-linux-x64-79b34eab.tgz]
-----> Installing ruby 2.4.3
-----> Update rubygems from 2.6.14 to 2.7.6
       Download [https://buildpacks.cloudfoundry.org/dependencies/rubygems/rubygems-2.7.6-67f714a5.tgz]
-----> Installing rubygems 2.7.6
-----> Installing node 6.13.0
       Download [https://buildpacks.cloudfoundry.org/dependencies/node/node-6.13.0-linux-x64-2724bdf3.tgz]
       **WARNING** You have the `.bundle/config` file checked into your repository
       It contains local state like the location of the installed bundle
       as well as configured git local gems, and other settings that should
-----> Installing dependencies using bundler 1.16.1
       not be shared between multiple checkouts of a single repo. Please
       remove the `.bundle/` folder from your repo and add it to your `.gitignore` file.
       Running: bundle install --without development:test --jobs=4 --retry=4 --path /tmp/contents693511504/deps/0/vendor_bundle --binstubs /tmp/contents693511504/deps/0/binstubs --deployment
       Fetching gem metadata from https://rubygems.org/.........
       Fetching rake 12.0.0
       Fetching concurrent-ruby 1.0.5
       Fetching erubi 1.7.0
       Installing erubi 1.7.0
       Installing minitest 5.11.3
       Installing concurrent-ruby 1.0.5
       Fetching thread_safe 0.3.6
       Fetching builder 3.2.3
       Fetching mini_portile2 2.3.0
       Fetching minitest 5.11.3
       Installing rake 12.0.0
       Installing thread_safe 0.3.6
       Installing builder 3.2.3
       Fetching crass 1.0.3
       Fetching rack 2.0.4
       Fetching nio4r 2.2.0
       Installing websocket-extensions 0.1.3
       Installing mini_portile2 2.3.0
       Installing rack 2.0.4
       Installing crass 1.0.3
       Installing nio4r 2.2.0 with native extensions
       Fetching websocket-extensions 0.1.3
       Installing mini_mime 1.0.0
       Installing arel 8.0.0
       Fetching mini_mime 1.0.0
       Fetching arel 8.0.0
       Fetching execjs 2.7.0
       Installing coffee-script-source 1.12.2
       Fetching thor 0.20.0
       Installing method_source 0.9.0
       Installing thor 0.20.0
       Using bundler 1.16.1
       Fetching method_source 0.9.0
       Fetching coffee-script-source 1.12.2
       Installing execjs 2.7.0
       Fetching ffi 1.9.22
       Installing multi_json 1.13.1
       Fetching multi_json 1.13.1
       Fetching puma 3.11.2
       Installing ffi 1.9.22 with native extensions
       Installing puma 3.11.2 with native extensions
       Fetching rb-fsevent 0.10.2
       Installing rb-fsevent 0.10.2
       Installing tilt 2.0.8
       Fetching sqlite3 1.3.13
       Fetching tilt 2.0.8
       Installing sqlite3 1.3.13 with native extensions
       Fetching turbolinks-source 5.1.0
       Fetching i18n 0.9.5
       Installing i18n 0.9.5
       Fetching tzinfo 1.2.5
       Fetching nokogiri 1.8.2
       Installing turbolinks-source 5.1.0
       Installing tzinfo 1.2.5
       Installing nokogiri 1.8.2 with native extensions
       Fetching websocket-driver 0.6.5
       Installing websocket-driver 0.6.5 with native extensions
       Fetching mail 2.7.0
       Installing mail 2.7.0
       Fetching rack-test 0.8.2
       Installing rack-test 0.8.2
       Fetching sprockets 3.7.1
       Installing sprockets 3.7.1
       Fetching uglifier 4.1.6
       Installing uglifier 4.1.6
       Installing turbolinks 5.1.0
       Fetching coffee-script 2.4.1
       Fetching activesupport 5.1.5
       Installing coffee-script 2.4.1
       Fetching turbolinks 5.1.0
       Fetching rb-inotify 0.9.10
       Fetching globalid 0.4.1
       Installing activesupport 5.1.5
       Installing sass-listen 4.0.0
       Fetching activejob 5.1.5
       Installing activerecord 5.1.5
       Installing rb-inotify 0.9.10
       Fetching jbuilder 2.7.0
       Installing jbuilder 2.7.0
       Fetching activerecord 5.1.5
       Installing globalid 0.4.1
       Fetching activemodel 5.1.5
       Fetching sass-listen 4.0.0
       Installing activemodel 5.1.5
       Installing activejob 5.1.5
       Fetching sass 3.5.5
       Installing sass 3.5.5
       Fetching rails-dom-testing 2.0.3
       Fetching loofah 2.2.0
       Installing rails-dom-testing 2.0.3
       Installing loofah 2.2.0
       Fetching actionview 5.1.5
       Installing rails-html-sanitizer 1.0.3
       Installing actionview 5.1.5
       Installing actionpack 5.1.5
       Fetching rails-html-sanitizer 1.0.3
       Fetching actionmailer 5.1.5
       Fetching actionpack 5.1.5
       Fetching actioncable 5.1.5
       Installing actioncable 5.1.5
       Fetching sprockets-rails 3.2.1
       Installing railties 5.1.5
       Installing sprockets-rails 3.2.1
       Fetching railties 5.1.5
       Installing actionmailer 5.1.5
       Fetching coffee-rails 4.2.2
       Fetching rails 5.1.5
       Fetching sass-rails 5.0.7
       Installing sass-rails 5.0.7
       Installing coffee-rails 4.2.2
       Installing rails 5.1.5
       Gems in the groups development and test were not installed.
-----> Regenerating bundler binstubs...
       Cleaning up the bundler cache.
       Bundle complete! 16 Gemfile dependencies, 56 gems now installed.
       Bundled gems are installed into `/tmp/contents693511504/deps/0/vendor_bundle`
-----> Creating runtime environment
Bundler::GemNotFound: Could not find rake-12.0.0 in any of the sources
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:82:in `materialize'
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:20:in `setup'
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:170:in `specs'
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Stopping instance f7ef067f-ac8f-404b-8b68-3fdaf4031be4
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:82:in `map!'
       **ERROR** Unable to write profile.d: Running 'rake secret'%!(EXTRA *exec.ExitError=exit status 1)
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:88:in `block in materialize'
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:237:in `specs_for'
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:226:in `requested_specs'
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:108:in `block in definition_method'
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler.rb:107:in `setup'
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/bundler/setup.rb:20:in `<top (required)>'
  /tmp/contents693511504/deps/0/ruby/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Failed to compile droplet: Failed to run all supply scripts: exit status 15
Exit status 223
Staging failed: STG: Exited with status 223
Destroying container
Successfully destroyed container
```

**Comment by dgodd** [comment]
Thanks @yusukesasamo, I'm looking ingto the problem right now

**Comment by dgodd** [comment]
@yusukesasamo I just pushed that sample app using both the built version of the buildpack 
```
cf push test-app -b https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.7.13/ruby-buildpack-v1.7.13.zip
```
and the master branch on github
```
cf push test-app2 -b https://github.com/cloudfoundry/ruby-buildpack
```
and both worked without any problems.

Are there any extra setup steps that I should be running?

**Comment by yusukesasamo** [comment]
@dgodd  Thank you for your confirmation. umm...... Now I'm checking why this difference happen...

**Comment by sclevine** [comment]
Closing due to inactivity. Let us know if this is still an issue.

**Comment by yusukesasamo** [comment]
@sclevine 
I could reproduce this issue, if we execute `bundle install` after that `.bundle` directory will be made.
So if we have this directly `cf push` fail when we use Over v1.7.0.
I could avoid this issue to add this directory name to `.cfignore` file.
Sorry I think I shouldn't post to this kind of closed ticket, but  I'd like to share this situation just in case.

Regards,
